version: "3"
services:
  next:
    container_name: next
    image: next
    build:
      context: "./app"
      dockerfile: Dockerfile
    expose:
      - 3004
    ports:
      - 3004:3004
    restart: on-failure
    networks:
      - web

  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - next
    networks:
      - web

networks:
  web:
    driver: bridge